services:
  db:
    image: postgres:latest
    container_name: vis_contas_db 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: vis_contas 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


